### ISSUE TITLE
Twarts conversation view

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#244] opened 2015-02-09 03:18 UTC
Clicking on a "Twart" (not exactly a fan of that word) should show the entire conversation not just itself.  
My guess a good way to do this is, the "Twart" view should have all of the tweets going up to the root level Twart, and then all twarts replied to it below it.  Then have the page jump to the selected twart.  This way the user can scroll up to see the context, and scroll down to see the replies.

**Comment by Wingar** [comment] 2015-02-09 03:20
I hate that word. But this is a duplicate of #235

**Closed** 2015-02-09 03:22 UTC
Labels: enhancement, Wishlist
