### ISSUE TITLE
Add a reply link to posts

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#158] opened 2014-12-28 03:58 UTC
Some how connect up the new post screen to allow to be replied, then have each post have a reply link.

Then probably the reply post screen would auto add in the (at)username as the first part of the 'tweet'

**Comment by walkeriniraq** [comment] 2015-01-01 20:22
Duplicate of #124

**Closed by walkeriniraq** 2015-01-01 20:22 UTC
Labels: duplicate, enhancement
